# Generated by Django 2.2 on 2019-04-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_cocktail_users'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_cocktails',
            field=models.ManyToManyField(to='core.Cocktail'),
        ),
    ]
