# Generated by Django 2.2 on 2019-04-24 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_favorite_cocktails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='favorite_cocktails',
            new_name='fav_cocktails',
        ),
    ]
