# Generated by Django 2.2 on 2019-04-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='dateModified',
            field=models.DateTimeField(blank=True),
        ),
    ]
