# Generated by Django 2.2 on 2019-04-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190423_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='dateModified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
