# Generated by Django 2.2 on 2019-04-24 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cocktail_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='users',
        ),
    ]
