# Generated by Django 2.2 on 2019-05-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_cocktail_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='strDrink',
            field=models.CharField(max_length=100),
        ),
    ]
